name: taming-env
channels:
  - pytorch
  - pyg
#  - nvidia                    # uncomment for gpu installation
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
#  - pytorch-cuda>=11.7         # specify your CUDA version
  - pytorch-lightning=2.0
  - torchmetrics=0.11
  - pyg>=2.0
  - pytorch-scatter
  - pytorch-sparse
  - pip
  - pip:
      - tensorboard
      - torch_spatiotemporal[experiment]==0.9.4
