defaults:
  - benchmarks
  - override dataset: engrad
  - override model: ttg_iso
  - override embedding: none
  # - override hydra/launcher: joblib
  - _self_

tags:
  - az_engrad
  - ${dataset.name}
  - ${model.name}

# neptune:
#   offline: False

az_analysis:
  use_mask: true
  plot_spacetime_scores: true
  node_order: null
  time_set: [0, 200]
  feat_set: [0, 2]
  time_filter: 1

#### Experiment params ########################################################
hydra:
  sweep:
    dir: logs/az_engrad/${now:%Y-%m-%d-%H-%M-%S}
  # launcher:
  #   n_jobs: 2  # number of parallel jobs
  # mode: MULTIRUN
  # sweeper:
  #   params:
  #     horizon: 1, 3, 6