defaults:
  - benchmarks
  - override dataset: engrad
  - override model: ttg_iso
  - override embedding: none
  - override hydra/launcher: joblib

hydra:
  run:
    # dir: logs/az_la_missing/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    dir: logs/v1/az_engrad/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: logs/v1/az_engrad/${now:%Y-%m-%d-%H-%M-%S}
  launcher:
    n_jobs: 2  # number of parallel jobs
  mode: MULTIRUN
  sweeper:
    params:
      model:  agcrn, ttg_iso

tags:
  - az_engrad
  - ${dataset.name}
  - ${model.name}

# neptune:
#   offline: False

az_analysis:
  use_mask: true
  plot_spacetime_scores: false
  node_order: null
  time_set: [4006, 4244]
  feat_set: [0, 1, 2]
  time_filter: 1
