defaults:
  - benchmarks
  - override dataset: la
  - override embedding: none
  - override hydra/launcher: joblib

hydra:
  run:
    dir: logs/v1/az_la_missing/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: logs/v1/az_la_missing/${now:%Y-%m-%d-%H-%M-%S}
  launcher:
    n_jobs: 2  # number of parallel jobs
  mode: MULTIRUN
  sweeper:
    params:
      model:  dcrnn, fcrnn, rnn, ttg_iso, agcrn, gwnet
      # model:  dcrnn, fcrnn, rnn, ttg_iso
      # model:  agcrn, gwnet

tags: az_la_missing

az_analysis:
  use_mask: false
  node_order: fit
  k_smooth_st: 5
  plot_spacetime_scores: true
  node_set: [30, 70]
  time_set: [1400, 1900]
  feat_set: [0, 3, 7, 11]
