defaults:
  - benchmarks
  - override dataset: la

hydra:
  run:
    dir: logs/az_la_missing/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/az_la_missing/${now:%Y-%m-%d-%H-%M-%S}

tags: az_la_missing

az_analysis:
  use_mask: false
  node_order: fit
  k_smooth_st: 5
  plot_spacetime_scores: true
  node_set: [30, 70]
  time_set: [1400, 1900]
  feat_set: [0, 3, 7, 11]
