defaults:
  - benchmarks
  - override embedding: none
  - override model: agcrn

hydra:
  run:
    dir: logs/az_pvwest/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/az_pvwest/${now:%Y-%m-%d-%H-%M-%S}

tags: az_pvwest

add_exogenous: false
dataset:
  hparams:
    mask_zeros: false

az_analysis:
  use_mask: false
  plot_spacetime_scores: false
  time_set: [0, 400]
  node_set: [0, 40]
  time_filter: 1
