defaults:
  - benchmarks
  - override model: agcrn
  - override dataset: pvwest

hydra:
  run:
    dir: logs/az_pvwest/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/az_pvwest/${now:%Y-%m-%d-%H-%M-%S}

tags: az_pvwest

add_exogenous: true
dataset:
  hparams:
    mask_zeros: true

az_analysis:
  use_mask: true
  plot_spacetime_scores: true
  node_order: null
  feat_set: [0, 1, 2]
  time_set: [4920, 5350] # centered around 3 days around the middle of the test set
  # node_set: [0, 300] 
  time_filter: 1
