defaults:
  - benchmarks
  - override model: ttg_iso
  - override dataset: pvwest

hydra:
  run:
    dir: logs/az_pvwest/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/az_pvwest/${now:%Y-%m-%d-%H-%M-%S}

tags: az_pvwest

add_exogenous: true
dataset:
  hparams:
    mask_zeros: true

az_analysis:
  use_mask: true
  plot_spacetime_scores: true
  node_order: null
  time_set: [0, 400]
  feat_set: [0, 2, 5]
  time_filter: 1
