defaults:
  - _self_
  - optimizer: lr0.01_gamma0.5
  - dataset: lgpvar
  - model: ttg_iso
  - embedding: none

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${model.name}/${dataset.name}/${hydra.job.num}

workers: 0
num_threads: 1

#### Training params ##########################################################
epochs: 200
patience: 50
batch_size: 128
train_batches: 1.0
grad_clip_val: 5
scale_axis: graph

regularization_weight: 1.0

neptune:
  online: true
  
#### Residual analysis params #################################################
ckpt: null
az_analysis:
  use_mask: true
  # multivariate: true
  node_order: null #fit
  plot_window: true
  plot_spacetime_scores: false
  time_filter: 10
  k_smooth_st: 1
  # downsample: 0.3
  # plot_dataset=True,
  # savefig: ${dataset.name}_${model.name}_${embedding.method}_${az_analysis.use_mask}_${now:%Y-%m-%d}${now:%H-%M-%S}


