# @package _global_

#### Dataset params ###########################################################
dataset:
  name: air
  splitting:
    method: air_quality
    val_len: 0.1
  connectivity:
    method: distance
    threshold: 0.1
    include_self: False
    layout: edge_index

#### Windowing params #########################################################
window: 24
horizon: 3
stride: 1

scale_target: True
mask_as_exog: True