# @package _global_

#### Dataset params ###########################################################
dataset:
  name: pems${dataset.id}
  id: 8
  splitting:
    val_len: 0.2
    test_len: 0.2
  connectivity:
    method: binary
    include_self: False
    layout: edge_index

#### Windowing params #########################################################
window: 12
horizon: 12
stride: 1

scale_target: False