# @package _global_

#### Dataset params ###########################################################
dataset:
  name: pvwest
  splitting:
    val_len: 0.1
    test_len: 0.2
  connectivity:
    method: distance
    threshold: 0.1
    include_self: False
    layout: edge_index

#### Windowing params #########################################################
window: 24
horizon: 6
stride: 1

scale_target: False
