# @package _global_

#### Dataset params ###########################################################
dataset:
  name: pvwest
  splitting:
    val_len: 0.1
    test_len: 0.2
  # splitting:
  #   method: AtTimeStepSplitter
  #   first_val_ts: [2006, 3, 1]
  #   last_val_ts: [2006, 3, 31]
  #   first_test_ts: [2006, 4, 1]
  #   last_test_ts: [2006, 9, 30]
  #   drop_following_steps: false
  connectivity:
    method: distance
    threshold: 0.1
    include_self: False
    layout: edge_index
    theta: 150
    knn: 8
    force_symmetric: True
  hparams:
    mask_zeros: false
    zones: west

#### Windowing params #########################################################
window: 24
horizon: 6
stride: 1

scale_target: true